security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$k/wk6qOOPwv5fqmm/G9cme.y4cXyAkbNgC.H22Q.Bu0yLvSdT9.Ry
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic:
              realm: administration

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }

