easy_admin:
  entities:
    AllUsers:
      class: App\Entity\User
      label: 'Users'
      form:
        fields:
          - { property: 'firstname', type_options: { required: true } }
          - { property: 'username', type_options: { required: true } }
          - { property: 'email', type: 'email', type_options: { required: true } }
    UsersHasBorrowed:
      class: App\Entity\User
      controller: App\Controller\Admin\UserAdminController
      list:
        dql_filter: 'bb.id IS NOT NULL AND bb.hasBeenReturned = 0'