easy_admin:
  entities:
    AllUsers:
      class: App\Entity\User
      label: 'Users'
      list:
        fields:
          - 'id'
          - 'firstname'
          - 'username'
          - 'hasBorrowed'
      form:
        fields:
          - { property: 'firstname', type_options: { required: true } }
          - { property: 'username', type_options: { required: true } }
          - { property: 'email', type: 'email', type_options: { required: true } }
          - { property: 'hasBorrowed', label: 'Has borrowed a book' }
    UsersHasBorrowed:
      class: App\Entity\User
      list:
        dql_filter: 'entity.hasBorrowed = 1'