easy_admin:
  design:
    menu:
      - { label: 'Dashboard', route: 'admin_dashboard', default: true }
      - label: 'Biblio'
      - label: 'Book'
        icon: book
        children:
          - { entity: 'Book', label: 'Book listing', icon: 'book', params: { sortField: 'id', sortDirection: 'DESC' }}
          - { label: 'Print book listing', icon: 'print', route: 'admin_books_listing_print' }
      - { entity: 'Category', icon: 'hashtag'}
      - { entity: 'BorrowedBook', label: 'Borrowed Books', icon: 'calendar'}
      - label: 'App'
      - { entity: 'AllUsers', label: 'All users', icon: 'user', params: { sortField: 'firstname', sortDirection: 'ASC' }}
      - { entity: 'UsersHasBorrowed', label: 'Borrowers', icon: 'calendar', params: { sortField: 'firstname', sortDirection: 'ASC' }}